const ProjectItemList = [
    {
        title: "VerseByVerse",
        category: "QA Automation Project",
        role: "QA Automation / Jr. SDET",
        summary: "Production full-stack Bible study platform with Playwright API automation for auth, notes CRUD, community workflows, cleanup, and CI-ready reporting.",
        technologies: ["Playwright", "API Testing", "MongoDB", "Node", "React", "GitHub Actions"],
        highlights: [
            "Designed 300+ manual, API, database, security, and regression test cases",
            "Automated authenticated API coverage for notes, communities, posts, validation, filtering, and unauthenticated access",
            "Prepared reusable helpers, test data cleanup, preflight checks, and HTML/JSON/JUnit artifacts",
        ],
        metrics: ["300+ test cases", "API automation", "CI-ready reports"],
        links: [
            {
                label: "Live Site",
                url: "https://versebyverse.website",
            },
            {
                label: "Test Automation",
                url: "https://github.com/LeeJay0126/versebyverse-quality-engineering",
            },
        ],
        accent: "qa",
        mark: "VbV",
    },
    {
        image: "midam.png",
        alt: "Midam logo",
        title: "Midam",
        category: "Development Project",
        role: "Frontend Developer",
        summary: "Responsive restaurant website with a QR-based digital menu flow, hosted through AWS S3 and Route 53.",
        technologies: ["React", "HTML5", "CSS", "Figma", "AWS"],
        highlights: [
            "Built production-facing menu and navigation flows",
            "Validated layout behavior across desktop and mobile breakpoints",
            "Supported a practical QR menu experience for customers",
        ],
        metrics: ["Production site", "Responsive UI"],
        isCompleted: true,
        isDeployed: true,
        accent: "web",
        links: [
            {
                label: "Live Site",
                url: "http://www.midam.ca/broadway/menu",
            },
        ],
    },
    {
        image: "EXpenditure.png",
        alt: "EXpenditure logo",
        title: "EXpenditure",
        category: "Development Project",
        role: "Full-Stack Developer",
        summary: "Expense tracking application built around account flows, persisted records, and backend-backed financial data management.",
        technologies: ["React", "Node", "PostgreSQL", "Express"],
        highlights: [
            "Implemented full-stack CRUD behavior",
            "Worked with relational data modeling and API routes",
            "Good candidate for future API and database validation coverage",
        ],
        metrics: ["CRUD workflows", "Backend API"],
        isCompleted: true,
        isDeployed: false,
        accent: "data",
        links: [],
    },
    {
        image: "LangaraTribe.png",
        alt: "Langara Tribe logo",
        title: "Langara Tribe",
        category: "Development Project",
        role: "Full-Stack Developer",
        summary: "Community-oriented web application using a MERN-style stack with user-facing interaction patterns.",
        technologies: ["React", "Node", "MongoDB", "Express"],
        highlights: [
            "Built frontend and backend application flows",
            "Worked with document-based data and REST API behavior",
            "Useful foundation for auth, permission, and integration testing practice",
        ],
        metrics: ["MERN stack", "Community flows"],
        isCompleted: true,
        isDeployed: false,
        accent: "community",
        links: [],
    },
    {
        image: "SalaryCalculator.png",
        alt: "Salary Calculator logo",
        title: "Salary Calculator",
        category: "Development Project",
        role: "Frontend Developer",
        summary: "Browser-based calculator focused on deterministic input/output behavior and clean client-side logic.",
        technologies: ["HTML", "CSS", "JavaScript"],
        highlights: [
            "Implemented calculation logic in plain JavaScript",
            "Focused on predictable form behavior and result display",
            "Straightforward target for future unit and boundary-value tests",
        ],
        metrics: ["Client-side logic", "Input validation"],
        isCompleted: true,
        isDeployed: false,
        accent: "logic",
        links: [],
    },
    {
        image: "Omnifood.png",
        alt: "Omnifood logo",
        title: "Omnifood",
        category: "Development Project",
        role: "Frontend Developer",
        summary: "Responsive marketing site focused on layout, visual hierarchy, and mobile-friendly page sections.",
        technologies: ["HTML", "CSS"],
        highlights: [
            "Built responsive page sections from static assets",
            "Practiced visual polish, spacing, and breakpoint behavior",
            "Useful baseline for UI regression and responsive layout checks",
        ],
        metrics: ["Responsive layout", "Static site"],
        isCompleted: true,
        isDeployed: false,
        accent: "ui",
        links: [],
    },
];

export default ProjectItemList;
